before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    binary: os-agent
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.board=Supervised
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 7

checksum:
  name_template: checksums.txt
  algorithm: sha512

changelog:
  sort: asc

nfpms:
  - maintainer: SmartAutomatic
    description: SmartAutomatic OS Agent
    homepage: https://smartautomatic.duckdns.org:8091
    section: default
    priority: extra
    bindir: /usr/bin
    formats:
      - deb
    dependencies:
      - udisks2
    replacements:
      386: i386
      amd64: x86_64
      arm64: aarch64
    contents:
      - src: contrib/saos-agent.service
        dst: /usr/lib/systemd/system/saos-agent.service
      - src: contrib/org.sas.conf
        dst: /etc/dbus-1/system.d/org.sas.conf
    scripts:
      postinstall: contrib/debian/postinstall.sh
      preremove: contrib/debian/preremove.sh
      postremove: contrib/debian/postremove.sh

release:
